---
- name: getting all hosts info
  hosts: localhost
  gather_facts: false
  vars:
    hostnew: []
  tasks:
    - name: group by the tasks
      set_fact:
        host_info: "{{hostnew.split(',')}}"

    - name: add host
      add_host:
        name: "{{ item }}"   
        group: all
      loop: "{{host_info}}"

- name: ping hosts
  hosts: all
  tasks:
    - name: print debug
      debug:
        msg: "the ips are {{ ansible_facts.all_ipv4_addresses }}"

    - name: print hostnae
      template:
        src: template-all.j2
        dest: /tmp/snow/output-{{inventory_hostname}}
      delegate_to: localhost
    
    - name: append into one
      assemble: 
        src: /tmp/snow/
        dest: final.csv
      delegate_to: localhost

...
